B4J=true
Group=Default Group
ModulesStructureVersion=1
Type=Class
Version=5.9
@EndOfDesignText@
#IgnoreWarnings:12
'Class Module
Sub Class_Globals
	'Private fx As JFX ' Uncomment if required. For B4j only
	Private JO As JavaObject
End Sub
'Initializes the object. You can add parameters to this method if needed.
Public Sub Initialize(Evt As JavaObject)
	'This is an autogenerated constructor, there may not be a matching constructor in the class, you will then have to remove the next line of code
	JO = Evt
End Sub

'Returns the wrapped object as JavaObject
Public Sub AsJavaObject As JavaObject
	Return JO
End Sub
'Marks this Event as consumed.
Public Sub Consume
	JO.RunMethod("consume",Null)
End Sub

'The Unicode character or sequence of characters associated with the key typed event.
Public Sub GetCharacter As String
	Return JO.RunMethod("getCharacter",Null)
End Sub
'The key code associated with the key in this key pressed or key released event.
Public Sub GetCode As KeyCode
	Dim Wrapper As KeyCode
	Wrapper.Initialize
	Wrapper.SetObject(JO.RunMethod("getCode",Null))
	Return Wrapper
End Sub
'Gets the event type of this event.
Public Sub GetEventType As JavaObject
	Return JO.RunMethod("getEventType",Null)
End Sub
'Returns the wrapped object as Object
Public Sub GetObject As Object
	Return JO
End Sub
'A String describing the key code, such as "HOME", "F1" or "A", for key pressed and key released events.
Public Sub GetText As String
	Return JO.RunMethod("getText",Null)
End Sub
'Returns whether or not the Alt modifier is down on this event.
Public Sub IsAltDown As Boolean
	Return JO.RunMethod("isAltDown",Null)
End Sub
'Returns whether or not the Control modifier is down on this event.
Public Sub IsControlDown As Boolean
	Return JO.RunMethod("isControlDown",Null)
End Sub
'Returns whether or not the Meta modifier is down on this event.
Public Sub IsMetaDown As Boolean
	Return JO.RunMethod("isMetaDown",Null)
End Sub
'Returns whether or not the Shift modifier is down on this event.
Public Sub IsShiftDown As Boolean
	Return JO.RunMethod("isShiftDown",Null)
End Sub
'Returns whether or not the host platform common shortcut modifier is down on this event.
Public Sub IsShortcutDown As Boolean
	Return JO.RunMethod("isShortcutDown",Null)
End Sub
'Returns a string representation of this KeyEvent object.
Public Sub ToString As String
	Return JO.RunMethod("toString",Null)
End Sub

'Comment if not needed
'Set the underlying Object, must be of correct type
Public Sub SetObject(Obj As Object)
	JO = Obj
End Sub

'Set the Tag for this object
Public Sub SetTag(Tag As Object)
	JO.RunMethod("setUserData",Array(Tag))
End Sub

'Get the Tag for this object
Public Sub GetTag As Object
	Dim Tag As Object = JO.RunMethod("getUserData",Null)
	If Tag = Null Then Tag = ""
	Return Tag
End Sub

